<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConnectionShareFile', 'default');

/**
 * BaseConnectionShareFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $fk_share_id
 * @property integer $fk_file_id
 * @property ConnectionShare $ConnectionShare
 * @property ConnectionFile $ConnectionFile
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConnectionShareFile extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('app_connection_share_file');
        $this->hasColumn('fk_share_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('fk_file_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));


        $this->index('app_connection_share_file_all_unique_index', array(
             'fields' => 
             array(
              0 => 'fk_share_id',
              1 => 'fk_file_id',
             ),
             'type' => 'unique',
             ));
        $this->index('app_connection_share_file_fk_share_id_index', array(
             'fields' => 
             array(
              0 => 'fk_share_id',
             ),
             ));
        $this->index('app_connection_share_file_fk_file_id_index', array(
             'fields' => 
             array(
              0 => 'fk_file_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ConnectionShare', array(
             'local' => 'fk_share_id',
             'foreign' => 'share_id'));

        $this->hasOne('ConnectionFile', array(
             'local' => 'fk_file_id',
             'foreign' => 'file_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}