<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConnectionFileContent', 'default');

/**
 * BaseConnectionFileContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $fk_file_id
 * @property integer $fk_file_version
 * @property text $content
 * @property ConnectionFile $ConnectionFile
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConnectionFileContent extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('app_user_connection_file_content');
        $this->hasColumn('fk_file_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('fk_file_version', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));


        $this->index('app_user_connection_file_content_fk_file_id_index', array(
             'fields' => 
             array(
              0 => 'fk_file_id',
             ),
             ));
        $this->index('app_user_connection_file_content_fk_file_id_fk_file_version_index', array(
             'fields' => 
             array(
              0 => 'fk_file_id',
              1 => 'fk_file_version',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ConnectionFile', array(
             'local' => 'fk_file_id',
             'foreign' => 'file_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'version',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             'tableName' => 'app_user_connection_file_content_version',
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}