<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserConnection', 'default');

/**
 * BaseUserConnection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $fk_user_id
 * @property integer $fk_connection_id
 * @property enum $type
 * @property User $User
 * @property Connection $Connection
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserConnection extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('app_user_connection');
        $this->hasColumn('fk_user_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('fk_connection_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'creator',
              1 => 'guest',
             ),
             'default' => 'guest',
             ));


        $this->index('app_user_connection_all_unique_index', array(
             'fields' => 
             array(
              0 => 'fk_user_id',
              1 => 'fk_connection_id',
             ),
             'type' => 'unique',
             ));
        $this->index('app_user_connection_fk_user_id_index', array(
             'fields' => 
             array(
              0 => 'fk_user_id',
             ),
             ));
        $this->index('app_user_connection_fk_connection_id_index', array(
             'fields' => 
             array(
              0 => 'fk_connection_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'fk_user_id',
             'foreign' => 'user_id'));

        $this->hasOne('Connection', array(
             'local' => 'fk_connection_id',
             'foreign' => 'connection_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}