<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConnectionShare', 'default');

/**
 * BaseConnectionShare
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $share_id
 * @property integer $fk_connection_id
 * @property string $name
 * @property boolean $is_enabled
 * @property boolean $is_readable
 * @property boolean $is_writable
 * @property boolean $send_notifications
 * @property Connection $Connection
 * @property Doctrine_Collection $ConnectionShareFile
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConnectionShare extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('app_connection_share');
        $this->hasColumn('share_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('fk_connection_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('is_enabled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_readable', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_writable', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('send_notifications', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));


        $this->index('app_connection_share_fk_connection_id_index', array(
             'fields' => 
             array(
              0 => 'fk_connection_id',
             ),
             ));
        $this->index('app_connection_share_share_id_is_enabled_id_index', array(
             'fields' => 
             array(
              0 => 'share_id',
              1 => 'is_enabled',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Connection', array(
             'local' => 'fk_connection_id',
             'foreign' => 'connection_id'));

        $this->hasMany('ConnectionShareFile', array(
             'local' => 'share_id',
             'foreign' => 'fk_share_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}