<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConnectionContent', 'default');

/**
 * BaseConnectionContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $fk_connection_id
 * @property text $content
 * @property Connection $Connection
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConnectionContent extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('app_user_connection_content');
        $this->hasColumn('fk_connection_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));


        $this->index('app_user_connection_content_fk_connection_id_index', array(
             'fields' => 
             array(
              0 => 'fk_connection_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Connection', array(
             'local' => 'fk_connection_id',
             'foreign' => 'connection_id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'version',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             'tableName' => 'app_user_connection_content_version',
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}