<?php

/**
 * ConnectionFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConnectionFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConnectionFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConnectionFile');
    }
}