actAs: [Timestampable]

User:
  connection: default
  tableName: app_user
  actAs: [Timestampable, SoftDelete]
  columns:
    user_id:
      primary: true
      autoincrement: true
      type: integer(8)
    username: string(50)
    password: string(50)
    email: string(50)
  indexes:
    app_user_email_password_index:
      fields: [email, password]

Group:
  connection: default
  tableName: app_groups
  actAs: [Timestampable, SoftDelete]
  columns:
    group_id:
      primary: true
      autoincrement: true
      type: integer(8)
    name: string(255)

UserGroup:
  connection: default
  tableName: app_user_group
  columns:
    fk_user_id:
      type: integer(8)
      primary: true
    fk_group_id:
      type: integer(8)
      primary: true
  indexes:
    app_user_group_all_index:
      fields: [fk_user_id, fk_group_id]
      type: unique
  relations:
    User:
      local: fk_user_id
      foreign: user_id
      type: one
    Group:
      local: fk_group_id
      foreign: group_id
      type: one

Connection:
  connection: default
  tableName: app_connection
  actAs: [Timestampable, SoftDelete]
  columns:
    connection_id:
      type: integer(8)
      autoincrement: true
      primary: true
    server: string(255)
    username: string(50)
    password: string(50)
    pathname: string(512)
    protocol: 
      type: enum
      values: [FTP]

ConnectionContent:
  connection: default
  tableName: app_user_connection_content
  actAs: 
    Timestampable:
    SoftDelete:
    Versionable:
      versionColumn: version
      className: %CLASS%Version
      auditLog: true
      tableName: app_user_connection_content_version
  columns:
    fk_connection_id:
      type: integer(8)
      primary: true
    content: text
  indexes:
    app_user_connection_content_fk_connection_id_index:
      fields: [fk_connection_id]
  relations:
    Connection:
      local: fk_connection_id
      foreign: connection_id
      type: one
      onDelete: CASCADE
      onUpdate: CASCADE

UserConnection:
  connection: default
  tableName: app_user_connection
  columns:
    fk_user_id:
      type: integer(8)
      primary: true
    fk_connection_id:
      type: integer(8)
      primary: true
    type:
      type: enum
      values: [creator, guest]
      default: guest
  indexes:
    app_user_connection_all_index:
      fields: [fk_user_id, fk_connection_id]
      type: unique
    app_user_connection_fk_user_id_index:
      fields: [fk_user_id]
  relations:
    User:
      local: fk_user_id
      foreign: user_id
      type: one
      onDelete: CASCADE
      onUpdate: CASCADE
    Connection:
      local: fk_connection_id
      foreign: connection_id
      type: one
      onDelete: CASCADE
      onUpdate: CASCADE