<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addappuserconnectioncontent extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('app_user_connection_content', array(
             'fk_connection_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'deleted_at' => 
             array(
              'notnull' => false,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'version' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
              'app_user_connection_content_fk_connection_id_index' => 
              array(
              'fields' => 
              array(
               0 => 'fk_connection_id',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'fk_connection_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('app_user_connection_content');
    }
}