<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Group', 'default');

/**
 * BaseGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property string $name
 * @property Doctrine_Collection $UserGroup
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroup extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('app_groups');
        $this->hasColumn('group_id', 'integer', 8, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserGroup', array(
             'local' => 'group_id',
             'foreign' => 'fk_group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}