<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConnectionFile', 'default');

/**
 * BaseConnectionFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $file_id
 * @property integer $fk_connection_id
 * @property string $filename
 * @property Connection $Connection
 * @property Doctrine_Collection $ConnectionFileContent
 * @property Doctrine_Collection $ConnectionShareFile
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConnectionFile extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('app_connection_file');
        $this->hasColumn('file_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('fk_connection_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '8',
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));


        $this->index('app_connection_file_fk_connection_id_index', array(
             'fields' => 
             array(
              0 => 'fk_connection_id',
             ),
             ));
        $this->index('app_connection_file_fk_connection_id_filename_unique_index', array(
             'fields' => 
             array(
              0 => 'fk_connection_id',
              1 => 'filename',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Connection', array(
             'local' => 'fk_connection_id',
             'foreign' => 'connection_id'));

        $this->hasMany('ConnectionFileContent', array(
             'local' => 'file_id',
             'foreign' => 'fk_file_id'));

        $this->hasMany('ConnectionShareFile', array(
             'local' => 'file_id',
             'foreign' => 'fk_file_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'version',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             'tableName' => 'app_connection_file_version',
             ));
        $this->actAs($timestampable0);
        $this->actAs($versionable0);
    }
}