<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserGroup', 'default');

/**
 * BaseUserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $fk_user_id
 * @property integer $fk_group_id
 * @property User $User
 * @property Group $Group
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserGroup extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('app_user_group');
        $this->hasColumn('fk_user_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('fk_group_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));


        $this->index('app_user_group_all_index', array(
             'fields' => 
             array(
              0 => 'fk_user_id',
              1 => 'fk_group_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'fk_user_id',
             'foreign' => 'user_id'));

        $this->hasOne('Group', array(
             'local' => 'fk_group_id',
             'foreign' => 'group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}