<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Connection', 'default');

/**
 * BaseConnection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $connection_id
 * @property string $server
 * @property string $username
 * @property string $password
 * @property string $pathname
 * @property enum $protocol
 * @property Doctrine_Collection $UserConnection
 * @property Doctrine_Collection $ConnectionFile
 * @property Doctrine_Collection $ConnectionShare
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConnection extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('app_connection');
        $this->hasColumn('connection_id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('server', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('username', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('password', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('pathname', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('protocol', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'FTP',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserConnection', array(
             'local' => 'connection_id',
             'foreign' => 'fk_connection_id'));

        $this->hasMany('ConnectionFile', array(
             'local' => 'connection_id',
             'foreign' => 'fk_connection_id'));

        $this->hasMany('ConnectionShare', array(
             'local' => 'connection_id',
             'foreign' => 'fk_connection_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}