<?php

/**
 * ConnectionContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConnectionContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConnectionContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConnectionContent');
    }
}