<?php

/**
 * ConnectionFileContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConnectionFileContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConnectionFileContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConnectionFileContent');
    }
}