<?php

/**
 * ConnectionShareTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConnectionShareTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConnectionShareTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConnectionShare');
    }
}