<?php

/**
 * UserConnectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserConnectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserConnectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserConnection');
    }
}