<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addappusergroup extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('app_user_group', array(
             'fk_user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             'fk_group_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'fk_user_id',
              1 => 'fk_group_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('app_user_group');
    }
}