<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addconnectioncontentversion extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('connection_content_version', array(
             'fk_connection_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'deleted_at' => 
             array(
              'notnull' => false,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'version' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'fk_connection_id',
              1 => 'version',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('connection_content_version');
    }
}