<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('app_user_connection', 'app_user_connection_fk_user_id_app_user_user_id', array(
             'name' => 'app_user_connection_fk_user_id_app_user_user_id',
             'local' => 'fk_user_id',
             'foreign' => 'user_id',
             'foreignTable' => 'app_user',
             ));
        $this->createForeignKey('app_user_connection', 'afac', array(
             'name' => 'afac',
             'local' => 'fk_connection_id',
             'foreign' => 'connection_id',
             'foreignTable' => 'app_connection',
             ));
        $this->createForeignKey('app_user_connection_content_version', 'afaf_1', array(
             'name' => 'afaf_1',
             'local' => 'fk_connection_id',
             'foreign' => 'fk_connection_id',
             'foreignTable' => 'app_user_connection_content',
             ));
        $this->createForeignKey('app_user_group', 'app_user_group_fk_user_id_app_user_user_id', array(
             'name' => 'app_user_group_fk_user_id_app_user_user_id',
             'local' => 'fk_user_id',
             'foreign' => 'user_id',
             'foreignTable' => 'app_user',
             ));
        $this->createForeignKey('app_user_group', 'app_user_group_fk_group_id_app_groups_group_id', array(
             'name' => 'app_user_group_fk_group_id_app_groups_group_id',
             'local' => 'fk_group_id',
             'foreign' => 'group_id',
             'foreignTable' => 'app_groups',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('app_user_connection', 'app_user_connection_fk_user_id_app_user_user_id');
        $this->dropForeignKey('app_user_connection', 'afac');
        $this->dropForeignKey('app_user_connection_content_version', 'afaf_1');
        $this->dropForeignKey('app_user_group', 'app_user_group_fk_user_id_app_user_user_id');
        $this->dropForeignKey('app_user_group', 'app_user_group_fk_group_id_app_groups_group_id');
    }
}